### ISSUE TITLE
请问这个生成这个keyword的方法怎么移植到其他主题上？

### ISSUE THREAD

**Issue by QingShui23** [JaxsonWang/Rebirth#2]
我目前用的素锦的魔改ghost主题，但是这个主题没做seo。我偶然间在v2ex上看到了你这个主题，发现做了seo优化，看了下代码，好像是渲染前替换掉了一些生成内容，但是不知道怎么移植。
不知道可否说下解决方案？
非常感谢。

**Comment by JaxsonWang** [comment]
您好：

- 我这边第一步价格编译的命令：[https://github.com/JaxsonWang/Rebirth/blob/master/package.json#L12](https://github.com/JaxsonWang/Rebirth/blob/master/package.json#L12) 让他执行 `config/build.js` 下的脚本
- `build.js`里面的方法大部分方法都是替换模板字符串，使用 `node` 的 `fs` 方法，替换字符串就是利用正则替换。

您可以研究下 `build.js` 里面的源码，虽然写得不咋的。

**Comment by QingShui23** [comment]
> 您好：
> 
> * 我这边第一步价格编译的命令：https://github.com/JaxsonWang/Rebirth/blob/master/package.json#L12 让他执行 `config/build.js` 下的脚本
> * `build.js`里面的方法大部分方法都是替换模板字符串，使用 `node` 的 `fs` 方法，替换字符串就是利用正则替换。
> 
> 您可以研究下 `build.js` 里面的源码，虽然写得不咋的。

你好，我刚刚仔细看了下，你这个keyword是写死的吗？感觉就直接限制了。
我刚刚考虑了一下其他办法，现在准备写在文章的meta_description里，手写一个keywords字段根据情况把meta_description读取出来

**Comment by JaxsonWang** [comment]
@QingShui23 在开发环境下是写死的，但是在打包 `build` 是根据 config.json 动态生成的字段，你可以去 dist 文件夹下 hbs 模板搜索相关关键词就知道了。

**Comment by QingShui23** [comment]
@JaxsonWang 嗯，我看了。但是config里面设置的什么关键字，最后生成的就是什么关键字。我
我现在想让每个页面有单独的keywords（在写文章的时候自定义），tag我现在是用来做分类的。不想把tag搞得太多。不过最后实在不行了还是只有用这个办法了。

**Comment by JaxsonWang** [comment]
@QingShui23 这种在模板里做不到，需要让 `ghost` 团队添加你想要的功能，或者改 `ghost` 内核源码才能支持...
