### ISSUE TITLE
请问标签和导航如何设置？

### ISSUE THREAD

**Issue by ninthDevilHAUNSTER** [JaxsonWang/Rebirth#4]
你好，我之前有用过你wordpress的插件，但是我wordpress的站点被我搞坏了。于是就跟随你的脚步装了Ghost，这是我现在的[博客地址](shaobaobaoer.cn)

我非常喜欢你的博客。希望不要把about页面中的个人信息给写死。

另外，请问标签和导航如何设置？

**Comment by JaxsonWang** [comment]
看了下源码，忘了把 `about` 页面抽取出来，我这俩天有时间修正这个问题。

`ghost` 不像 wordpress 有菜单的概念，他是把标签当作菜单，你可以去摸索下。

**Comment by ninthDevilHAUNSTER** [comment]
![图片标题](https://leanote.com/api/file/getImage?fileId=5ed62590ab644125c10018ac)

昂，我的意思是问 两栏在哪里设置呀

**Comment by JaxsonWang** [comment]
@ninthDevilHAUNSTER 后台中的 `Design` - `SECONDARY NAVIGATION` 这边作为页脚导航

**Comment by ninthDevilHAUNSTER** [comment]
喔喔，那页脚的标签是咋设置的呀！

**Comment by JaxsonWang** [comment]
@ninthDevilHAUNSTER 标签是在后台的 `Tags` 页面，这个需要配合 https://github.com/JaxsonWang/Rebirth/blob/master/site.config.example.json#L27

> 出现 site.config.json 的标签会在标签云展示忽略的标签名称

**Comment by JaxsonWang** [comment]
@ninthDevilHAUNSTER https://github.com/JaxsonWang/Rebirth/commit/b96bf2037825fefe769aae6525859b0434bf8829

已更新：
```json
"siteAboutName": "关于个人的模板 - 个人姓名",
"siteAboutEmail": "关于个人的模板 - 个人邮箱",
"siteAboutPosition": "关于个人的模板 - 个人职位",
"siteAboutWebsite": "关于个人的模板 - 个人网站"
```

请注意更新 `site.config.json` 文件
