### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by eanraig** [JaxsonWang/Rebirth#6]
使用主题是发现，在播放器在右键点击视频统计信息，会打开一个空白标签页。默认主题和本地hexo上测试并未发现同样问题。
![1.png](https://i.loli.net/2020/09/16/3SueYEao4qdA5b2.png)
![2.png](https://i.loli.net/2020/09/16/lSjgUQYxb8k51vd.png)

**Comment by JaxsonWang** [comment]
目前猜测：https://github.com/JaxsonWang/Rebirth/blob/master/src/js/ghost/global.js#L12-L14

解决这个也很好解决，排查菜单就行了，我后面有时间优化下。

PS：目前精力放在新主题上。

**Comment by JaxsonWang** [comment]
to [https://github.com/JaxsonWang/Rebirth/commit/d79f61aaa5aa5a6cbf2fa4bc98db55ff38d0fff7](https://github.com/JaxsonWang/Rebirth/commit/d79f61aaa5aa5a6cbf2fa4bc98db55ff38d0fff7)
